In [3]:
from IPython.display import HTML

HTML('''<script>
code_show=true; 
function code_toggle() {
 if (code_show){
 $('div.input').hide();
 } else {
 $('div.input').show();
 }
 code_show = !code_show
} 
$( document ).ready(code_toggle);
</script>
<form action="javascript:code_toggle()"><input type="submit" value="Show/Hide code"></form>''')

# 0. Load package

In [1]:
#!/usr/bin/python
# -*- coding: utf-8 -*-
import pandas as pd
import numpy as np
from ckip_transformers.nlp import CkipWordSegmenter, CkipPosTagger, CkipNerChunker


# 1. Load  data 

In [2]:
document1 = ["（台灣英文新聞／醫藥組　綜合報導）中央流行疫情指揮中心今(4)日公布國內新增2例武漢肺炎（COVID-19）境外移入確定病例(案960、961)，分別自奈及利亞及菲律賓入境。",
"指揮中心表示，案960為奈及利亞籍50多歲男性，長期居住台灣，並持有我國居留證，今(2021)年1月8日返回奈及利亞奔喪，在當地曾於1月18日出現輕微咳嗽，經自行服藥後症狀緩解。",
"個案2月28日返台，持有搭機前3日內檢驗陰性報告，入境後至防疫旅館檢疫，3月2日因全身倦怠及有慢性病之就醫需求，由衛生單位安排就醫採檢，於今日確診。個案就醫時接觸之相關人員皆有適當防護，故無匡列接觸者。",
"案961為菲律賓籍20多歲男性移工，今年2月9日來台工作，持有搭機前3日內檢驗陰性報告，入境後至集中檢疫所檢疫，2月22日接受檢疫期滿前採檢，結果為陰性。",
"個案檢疫期滿後，由仲介安排至其他住所自主健康管理，2月26日搭乘專車至醫院自費採檢，因核酸檢測未確定，27日先行收治住院隔離，同日及3月2日進行核酸檢驗，於今日確診。",
"個案入境至今無症狀，已掌握個案接觸者共9人，其中同車移工8人未確實佩戴口罩，列居家隔離，司機1人因有適當防護，列自主健康管理。",
"指揮中心統計，截至目前國內累計960例確診，分別為844例境外移入，77例本土病例，36例敦睦艦隊、2例航空器感染及1例不明；另1例(案530)移除為空號。確診個案中9人死亡、928人解除隔離、23人住院隔離中。"]
document2 =["〔記者林惠琴／台北報導〕中央流行疫情指揮中心今日公布，武漢肺炎（新型冠狀病毒病，COVID-19）新增2例境外移入，分別自奈及利亞及菲律賓入境。",
"指揮中心發言人莊人祥表示，新增的案960為奈及利亞籍50多歲男性，長期居住台灣，並持有我國居留證，今年1月8日返回奈及利亞奔喪，在當地曾於1月18日出現輕微咳嗽，經自行服藥後症狀緩解。",
"該名個案2月28日返台，持有搭機前3日內檢驗陰性報告，入境後至防疫旅館檢疫，3月2日因全身倦怠及有慢性病之就醫需求，由衛生單位安排就醫採檢，於今日確診。就醫時接觸相關人員皆有適當防護，無匡列接觸者。",
"案961為菲律賓籍20多歲男性移工，今年2月9日來台工作，持有搭機前3日內檢驗陰性報告，入境後至集中檢疫所檢疫，2月22日接受檢疫期滿前採檢，結果為陰性，檢疫期滿後，由仲介安排至其他住所自主健康管理，2月26日搭乘專車至醫院自費採檢，因核酸檢測未確定，27日先行收治住院隔離，同日及3月2日進行核酸檢驗，於今日確診。",
"該名個案入境至今無症狀，已掌握個案接觸者共9人，其中同車移工8人未確實佩戴口罩，列居家隔離，司機1人因有適當防護，列自主健康管理。",
"指揮中心統計，截至目前國內累計960例武漢肺炎，分別為844例境外移入，77例本土病例，36例敦睦艦隊、2例航空器感染及1例不明；另1例（案530）移除為空號。確診個案中9人死亡、928人解除隔離、23人住院隔離中。",]
text = []
text.append(document1)
text.append(document2)

print("文件一")
for doc1 in document1:
    print(doc1)
print("文件二")
for doc2 in document2:
    print(doc2)

文件一
（台灣英文新聞／醫藥組　綜合報導）中央流行疫情指揮中心今(4)日公布國內新增2例武漢肺炎（COVID-19）境外移入確定病例(案960、961)，分別自奈及利亞及菲律賓入境。
指揮中心表示，案960為奈及利亞籍50多歲男性，長期居住台灣，並持有我國居留證，今(2021)年1月8日返回奈及利亞奔喪，在當地曾於1月18日出現輕微咳嗽，經自行服藥後症狀緩解。
個案2月28日返台，持有搭機前3日內檢驗陰性報告，入境後至防疫旅館檢疫，3月2日因全身倦怠及有慢性病之就醫需求，由衛生單位安排就醫採檢，於今日確診。個案就醫時接觸之相關人員皆有適當防護，故無匡列接觸者。
案961為菲律賓籍20多歲男性移工，今年2月9日來台工作，持有搭機前3日內檢驗陰性報告，入境後至集中檢疫所檢疫，2月22日接受檢疫期滿前採檢，結果為陰性。
個案檢疫期滿後，由仲介安排至其他住所自主健康管理，2月26日搭乘專車至醫院自費採檢，因核酸檢測未確定，27日先行收治住院隔離，同日及3月2日進行核酸檢驗，於今日確診。
個案入境至今無症狀，已掌握個案接觸者共9人，其中同車移工8人未確實佩戴口罩，列居家隔離，司機1人因有適當防護，列自主健康管理。
指揮中心統計，截至目前國內累計960例確診，分別為844例境外移入，77例本土病例，36例敦睦艦隊、2例航空器感染及1例不明；另1例(案530)移除為空號。確診個案中9人死亡、928人解除隔離、23人住院隔離中。
文件二
〔記者林惠琴／台北報導〕中央流行疫情指揮中心今日公布，武漢肺炎（新型冠狀病毒病，COVID-19）新增2例境外移入，分別自奈及利亞及菲律賓入境。
指揮中心發言人莊人祥表示，新增的案960為奈及利亞籍50多歲男性，長期居住台灣，並持有我國居留證，今年1月8日返回奈及利亞奔喪，在當地曾於1月18日出現輕微咳嗽，經自行服藥後症狀緩解。
該名個案2月28日返台，持有搭機前3日內檢驗陰性報告，入境後至防疫旅館檢疫，3月2日因全身倦怠及有慢性病之就醫需求，由衛生單位安排就醫採檢，於今日確診。就醫時接觸相關人員皆有適當防護，無匡列接觸者。
案961為菲律賓籍20多歲男性移工，今年2月9日來台工作，持有搭機前3日內檢驗陰性報告，入境後至集中檢疫所檢疫，2月22日接受檢疫期滿前採檢，結果為陰性，檢疫期滿後，由仲介安排至其他住所自主健康管理，2月26日搭乘專車至醫院自

# 2. Load CKIP model and Tokenization

In [3]:
ws_driver  = CkipWordSegmenter(level=3)
pos_driver = CkipPosTagger(level=3)
ner_driver = CkipNerChunker(level=3)

In [4]:
text

[['（台灣英文新聞／醫藥組\u3000綜合報導）中央流行疫情指揮中心今(4)日公布國內新增2例武漢肺炎（COVID-19）境外移入確定病例(案960、961)，分別自奈及利亞及菲律賓入境。',
  '指揮中心表示，案960為奈及利亞籍50多歲男性，長期居住台灣，並持有我國居留證，今(2021)年1月8日返回奈及利亞奔喪，在當地曾於1月18日出現輕微咳嗽，經自行服藥後症狀緩解。',
  '個案2月28日返台，持有搭機前3日內檢驗陰性報告，入境後至防疫旅館檢疫，3月2日因全身倦怠及有慢性病之就醫需求，由衛生單位安排就醫採檢，於今日確診。個案就醫時接觸之相關人員皆有適當防護，故無匡列接觸者。',
  '案961為菲律賓籍20多歲男性移工，今年2月9日來台工作，持有搭機前3日內檢驗陰性報告，入境後至集中檢疫所檢疫，2月22日接受檢疫期滿前採檢，結果為陰性。',
  '個案檢疫期滿後，由仲介安排至其他住所自主健康管理，2月26日搭乘專車至醫院自費採檢，因核酸檢測未確定，27日先行收治住院隔離，同日及3月2日進行核酸檢驗，於今日確診。',
  '個案入境至今無症狀，已掌握個案接觸者共9人，其中同車移工8人未確實佩戴口罩，列居家隔離，司機1人因有適當防護，列自主健康管理。',
  '指揮中心統計，截至目前國內累計960例確診，分別為844例境外移入，77例本土病例，36例敦睦艦隊、2例航空器感染及1例不明；另1例(案530)移除為空號。確診個案中9人死亡、928人解除隔離、23人住院隔離中。'],
 ['〔記者林惠琴／台北報導〕中央流行疫情指揮中心今日公布，武漢肺炎（新型冠狀病毒病，COVID-19）新增2例境外移入，分別自奈及利亞及菲律賓入境。',
  '指揮中心發言人莊人祥表示，新增的案960為奈及利亞籍50多歲男性，長期居住台灣，並持有我國居留證，今年1月8日返回奈及利亞奔喪，在當地曾於1月18日出現輕微咳嗽，經自行服藥後症狀緩解。',
  '該名個案2月28日返台，持有搭機前3日內檢驗陰性報告，入境後至防疫旅館檢疫，3月2日因全身倦怠及有慢性病之就醫需求，由衛生單位安排就醫採檢，於今日確診。就醫時接觸相關人員皆有適當防護，無匡列接觸者。',
  '案961為菲律賓籍20多歲男性移工，今年2月9日來台工作，持有搭機前3日內檢驗陰性報告，入境後至集中檢疫所檢疫，2月22日接

In [5]:
doc_ws= []

for doc in text:
    doc_ws.append(ws_driver(doc))



Inference: 100%|██████████| 1/1 [00:00<00:00,  1.18it/s]


In [6]:
for doc,ws in zip(text,doc_ws):
    for i in range(len(doc)):
        print("document {}".format(i))
        print(  doc[i],"\n",ws[i] )

document 0
（台灣英文新聞／醫藥組　綜合報導）中央流行疫情指揮中心今(4)日公布國內新增2例武漢肺炎（COVID-19）境外移入確定病例(案960、961)，分別自奈及利亞及菲律賓入境。 
 ['（', '台灣', '英文', '新聞', '／', '醫藥組', '\u3000', '綜合', '報導', '）', '中央', '流行', '疫情', '指揮', '中心', '今', '(4)', '日', '公布', '國內', '新增', '2', '例', '武漢', '肺炎', '（', 'COVID-19', '）', '境外', '移入', '確定', '病例', '(', '案', '960', '、', '961', ')', '，', '分別', '自', '奈及利亞', '及', '菲律賓', '入境', '。']
document 1
指揮中心表示，案960為奈及利亞籍50多歲男性，長期居住台灣，並持有我國居留證，今(2021)年1月8日返回奈及利亞奔喪，在當地曾於1月18日出現輕微咳嗽，經自行服藥後症狀緩解。 
 ['指揮', '中心', '表示', '，', '案', '960', '為', '奈及利亞籍', '50多', '歲', '男性', '，', '長期', '居住', '台灣', '，', '並', '持有', '我國', '居留證', '，', '今', '(2021', ')', '年', '1月', '8日', '返回', '奈及利亞', '奔喪', '，', '在', '當地', '曾', '於', '1月', '18日', '出現', '輕微', '咳嗽', '，', '經', '自行', '服藥', '後', '症狀', '緩解', '。']
document 2
個案2月28日返台，持有搭機前3日內檢驗陰性報告，入境後至防疫旅館檢疫，3月2日因全身倦怠及有慢性病之就醫需求，由衛生單位安排就醫採檢，於今日確診。個案就醫時接觸之相關人員皆有適當防護，故無匡列接觸者。 
 ['個案', '2月', '28日', '返台', '，', '持有', '搭機', '前', '3', '日', '內', '檢驗', '陰性', '報告', '，', '入境', '後', '至', '防疫', '旅館', '檢疫', '，

# 3. Similarity method compare
1. levenshtein & normalized_levenshtein
2. LongestCommonSubsequence & metric_lcs
3. Jaccard coefficient
4. Dice coefficient
5. Overlap coefficient
6. cosine similarity

## 1. levenshtein & normalized_levenshtein

In [7]:
# import distance
from strsimpy.levenshtein import Levenshtein ## https://github.com/luozhouyang/python-string-similarity
from strsimpy.normalized_levenshtein import NormalizedLevenshtein
doc1_index = 0
levenshtein = Levenshtein()
normalized_levenshtein = NormalizedLevenshtein()
for ws in doc_ws[0]:
    nlevenshtein=[]
    doc2_index= 0
    for ws_x in doc_ws[1]:
        
        # print(doc1_index,text[0][doc1_index])
        # print(doc2_index,text[1][doc2_index])  ## sentence & sentence pair compare
        # print("Levenshtein",distance.nlevenshtein(ws, ws_x))
        # hamming needs the same length strings
        
        # nlevenshtein.append(levenshtein.distance(ws, ws_x)) #levenshtein
        nlevenshtein.append(normalized_levenshtein.distance(ws, ws_x)) #normalized_levenshtein
        doc2_index+=1
    
    print(doc1_index,text[0][doc1_index])
    print(nlevenshtein.index(min(nlevenshtein)),text[1][nlevenshtein.index(min(nlevenshtein))])
    print("normalized_levenshtein",min(nlevenshtein)) 
    doc1_index+=1

0 （台灣英文新聞／醫藥組　綜合報導）中央流行疫情指揮中心今(4)日公布國內新增2例武漢肺炎（COVID-19）境外移入確定病例(案960、961)，分別自奈及利亞及菲律賓入境。
0 〔記者林惠琴／台北報導〕中央流行疫情指揮中心今日公布，武漢肺炎（新型冠狀病毒病，COVID-19）新增2例境外移入，分別自奈及利亞及菲律賓入境。
normalized_levenshtein 0.5869565217391305
1 指揮中心表示，案960為奈及利亞籍50多歲男性，長期居住台灣，並持有我國居留證，今(2021)年1月8日返回奈及利亞奔喪，在當地曾於1月18日出現輕微咳嗽，經自行服藥後症狀緩解。
1 指揮中心發言人莊人祥表示，新增的案960為奈及利亞籍50多歲男性，長期居住台灣，並持有我國居留證，今年1月8日返回奈及利亞奔喪，在當地曾於1月18日出現輕微咳嗽，經自行服藥後症狀緩解。
normalized_levenshtein 0.16326530612244897
2 個案2月28日返台，持有搭機前3日內檢驗陰性報告，入境後至防疫旅館檢疫，3月2日因全身倦怠及有慢性病之就醫需求，由衛生單位安排就醫採檢，於今日確診。個案就醫時接觸之相關人員皆有適當防護，故無匡列接觸者。
2 該名個案2月28日返台，持有搭機前3日內檢驗陰性報告，入境後至防疫旅館檢疫，3月2日因全身倦怠及有慢性病之就醫需求，由衛生單位安排就醫採檢，於今日確診。就醫時接觸相關人員皆有適當防護，無匡列接觸者。
normalized_levenshtein 0.07936507936507936
3 案961為菲律賓籍20多歲男性移工，今年2月9日來台工作，持有搭機前3日內檢驗陰性報告，入境後至集中檢疫所檢疫，2月22日接受檢疫期滿前採檢，結果為陰性。
3 案961為菲律賓籍20多歲男性移工，今年2月9日來台工作，持有搭機前3日內檢驗陰性報告，入境後至集中檢疫所檢疫，2月22日接受檢疫期滿前採檢，結果為陰性，檢疫期滿後，由仲介安排至其他住所自主健康管理，2月26日搭乘專車至醫院自費採檢，因核酸檢測未確定，27日先行收治住院隔離，同日及3月2日進行核酸檢驗，於今日確診。
normalized_levenshtein 0.5161290322580645
4 個案檢疫期滿後，由仲介安排至其他住所自主健康管理，2月26

## 2. LongestCommonSubsequence & metric_lcs


In [8]:
from strsimpy.longest_common_subsequence import LongestCommonSubsequence
from strsimpy.metric_lcs import MetricLCS
lcs = LongestCommonSubsequence()
metric_lcs = MetricLCS()
##1 - |LCS(s1, s2)| / max(|s1|, |s2|)
doc1_index = 0
for ws in doc_ws[0]:
    LCS=[]
    doc2_index= 0
    for ws_x in doc_ws[1]:
        
        # print(doc1_index,text[0][doc1_index])
        # print(doc2_index,text[1][doc2_index])  ## sentence & sentence pair compare
        # print("Levenshtein",distance.nlevenshtein(ws, ws_x))
        # hamming needs the same length strings
        
    
        # LCS.append(lcs.distance(ws, ws_x)) #LCS
        LCS.append(metric_lcs.distance(ws, ws_x)) #metric_lcs
        # print(metric_lcs.distance(s1, s2))
        doc2_index+=1
    
    print(doc1_index,text[0][doc1_index])
    print(LCS.index(min(LCS)),text[1][LCS.index(min(LCS))])
    print("metric_lcs",min(LCS)) 
    doc1_index+=1

0 （台灣英文新聞／醫藥組　綜合報導）中央流行疫情指揮中心今(4)日公布國內新增2例武漢肺炎（COVID-19）境外移入確定病例(案960、961)，分別自奈及利亞及菲律賓入境。
0 〔記者林惠琴／台北報導〕中央流行疫情指揮中心今日公布，武漢肺炎（新型冠狀病毒病，COVID-19）新增2例境外移入，分別自奈及利亞及菲律賓入境。
metric_lcs 0.5217391304347826
1 指揮中心表示，案960為奈及利亞籍50多歲男性，長期居住台灣，並持有我國居留證，今(2021)年1月8日返回奈及利亞奔喪，在當地曾於1月18日出現輕微咳嗽，經自行服藥後症狀緩解。
1 指揮中心發言人莊人祥表示，新增的案960為奈及利亞籍50多歲男性，長期居住台灣，並持有我國居留證，今年1月8日返回奈及利亞奔喪，在當地曾於1月18日出現輕微咳嗽，經自行服藥後症狀緩解。
metric_lcs 0.10204081632653061
2 個案2月28日返台，持有搭機前3日內檢驗陰性報告，入境後至防疫旅館檢疫，3月2日因全身倦怠及有慢性病之就醫需求，由衛生單位安排就醫採檢，於今日確診。個案就醫時接觸之相關人員皆有適當防護，故無匡列接觸者。
2 該名個案2月28日返台，持有搭機前3日內檢驗陰性報告，入境後至防疫旅館檢疫，3月2日因全身倦怠及有慢性病之就醫需求，由衛生單位安排就醫採檢，於今日確診。就醫時接觸相關人員皆有適當防護，無匡列接觸者。
metric_lcs 0.04761904761904767
3 案961為菲律賓籍20多歲男性移工，今年2月9日來台工作，持有搭機前3日內檢驗陰性報告，入境後至集中檢疫所檢疫，2月22日接受檢疫期滿前採檢，結果為陰性。
3 案961為菲律賓籍20多歲男性移工，今年2月9日來台工作，持有搭機前3日內檢驗陰性報告，入境後至集中檢疫所檢疫，2月22日接受檢疫期滿前採檢，結果為陰性，檢疫期滿後，由仲介安排至其他住所自主健康管理，2月26日搭乘專車至醫院自費採檢，因核酸檢測未確定，27日先行收治住院隔離，同日及3月2日進行核酸檢驗，於今日確診。
metric_lcs 0.5161290322580645
4 個案檢疫期滿後，由仲介安排至其他住所自主健康管理，2月26日搭乘專車至醫院自費採檢，因核酸檢測未確定，27日先行收治住院隔離，同日及3月2日進行核酸檢驗，

## 3. Jaccard coefficient


In [9]:
## jaccard

def Jaccrad(doc1, doc2):#terms_reference为源句子，terms_model为候选句子
    doc1 = set(doc1)
    doc2 = set(doc2)
    temp=0
    for i in doc1:
        if i in doc2:
            temp=temp+1
    fenmu=len(doc2)+len(doc1)-temp #聯集
    jaccard_coefficient=float(temp/fenmu)#交集
    return jaccard_coefficient
doc1_index = 0
for ws in doc_ws[0]:
    jaccard_=[]
    doc2_index= 0
    for ws_x in doc_ws[1]:
        

        jaccard_.append(Jaccrad(ws, ws_x)) #jaccard
        doc2_index+=1
    
    print(doc1_index,text[0][doc1_index])
    print(jaccard_.index(max(jaccard_)),text[1][jaccard_.index(max(jaccard_))])
    print("jaccard_coefficient",max(jaccard_)) 
    doc1_index+=1

0 （台灣英文新聞／醫藥組　綜合報導）中央流行疫情指揮中心今(4)日公布國內新增2例武漢肺炎（COVID-19）境外移入確定病例(案960、961)，分別自奈及利亞及菲律賓入境。
0 〔記者林惠琴／台北報導〕中央流行疫情指揮中心今日公布，武漢肺炎（新型冠狀病毒病，COVID-19）新增2例境外移入，分別自奈及利亞及菲律賓入境。
jaccard_coefficient 0.46296296296296297
1 指揮中心表示，案960為奈及利亞籍50多歲男性，長期居住台灣，並持有我國居留證，今(2021)年1月8日返回奈及利亞奔喪，在當地曾於1月18日出現輕微咳嗽，經自行服藥後症狀緩解。
1 指揮中心發言人莊人祥表示，新增的案960為奈及利亞籍50多歲男性，長期居住台灣，並持有我國居留證，今年1月8日返回奈及利亞奔喪，在當地曾於1月18日出現輕微咳嗽，經自行服藥後症狀緩解。
jaccard_coefficient 0.8085106382978723
2 個案2月28日返台，持有搭機前3日內檢驗陰性報告，入境後至防疫旅館檢疫，3月2日因全身倦怠及有慢性病之就醫需求，由衛生單位安排就醫採檢，於今日確診。個案就醫時接觸之相關人員皆有適當防護，故無匡列接觸者。
2 該名個案2月28日返台，持有搭機前3日內檢驗陰性報告，入境後至防疫旅館檢疫，3月2日因全身倦怠及有慢性病之就醫需求，由衛生單位安排就醫採檢，於今日確診。就醫時接觸相關人員皆有適當防護，無匡列接觸者。
jaccard_coefficient 0.9433962264150944
3 案961為菲律賓籍20多歲男性移工，今年2月9日來台工作，持有搭機前3日內檢驗陰性報告，入境後至集中檢疫所檢疫，2月22日接受檢疫期滿前採檢，結果為陰性。
3 案961為菲律賓籍20多歲男性移工，今年2月9日來台工作，持有搭機前3日內檢驗陰性報告，入境後至集中檢疫所檢疫，2月22日接受檢疫期滿前採檢，結果為陰性，檢疫期滿後，由仲介安排至其他住所自主健康管理，2月26日搭乘專車至醫院自費採檢，因核酸檢測未確定，27日先行收治住院隔離，同日及3月2日進行核酸檢驗，於今日確診。
jaccard_coefficient 0.5373134328358209
4 個案檢疫期滿後，由仲介安排至其他住所自主健康管理，2月26日搭乘專車至醫院自費採檢，

## 4. Dice coefficient


In [10]:
## dice

def Dice(doc1, doc2):
    doc1 = set(doc1)
    doc2 = set(doc2)
    temp=0
    for i in doc1:
        if i in doc2:
            temp=temp+1
    dice_coefficient=float(2*temp/(len(doc2)+len(doc1)))#交集
    return dice_coefficient
doc1_index = 0
for ws in doc_ws[0]:
    dice_=[]
    doc2_index= 0
    for ws_x in doc_ws[1]:
        

        dice_.append(Dice(ws, ws_x)) #dice
        doc2_index+=1
    
    print(doc1_index,text[0][doc1_index])
    print(dice_.index(max(dice_)),text[1][dice_.index(max(dice_))])
    print("dice_coefficient",max(dice_)) 
    doc1_index+=1

0 （台灣英文新聞／醫藥組　綜合報導）中央流行疫情指揮中心今(4)日公布國內新增2例武漢肺炎（COVID-19）境外移入確定病例(案960、961)，分別自奈及利亞及菲律賓入境。
0 〔記者林惠琴／台北報導〕中央流行疫情指揮中心今日公布，武漢肺炎（新型冠狀病毒病，COVID-19）新增2例境外移入，分別自奈及利亞及菲律賓入境。
dice_coefficient 0.6329113924050633
1 指揮中心表示，案960為奈及利亞籍50多歲男性，長期居住台灣，並持有我國居留證，今(2021)年1月8日返回奈及利亞奔喪，在當地曾於1月18日出現輕微咳嗽，經自行服藥後症狀緩解。
1 指揮中心發言人莊人祥表示，新增的案960為奈及利亞籍50多歲男性，長期居住台灣，並持有我國居留證，今年1月8日返回奈及利亞奔喪，在當地曾於1月18日出現輕微咳嗽，經自行服藥後症狀緩解。
dice_coefficient 0.8941176470588236
2 個案2月28日返台，持有搭機前3日內檢驗陰性報告，入境後至防疫旅館檢疫，3月2日因全身倦怠及有慢性病之就醫需求，由衛生單位安排就醫採檢，於今日確診。個案就醫時接觸之相關人員皆有適當防護，故無匡列接觸者。
2 該名個案2月28日返台，持有搭機前3日內檢驗陰性報告，入境後至防疫旅館檢疫，3月2日因全身倦怠及有慢性病之就醫需求，由衛生單位安排就醫採檢，於今日確診。就醫時接觸相關人員皆有適當防護，無匡列接觸者。
dice_coefficient 0.970873786407767
3 案961為菲律賓籍20多歲男性移工，今年2月9日來台工作，持有搭機前3日內檢驗陰性報告，入境後至集中檢疫所檢疫，2月22日接受檢疫期滿前採檢，結果為陰性。
3 案961為菲律賓籍20多歲男性移工，今年2月9日來台工作，持有搭機前3日內檢驗陰性報告，入境後至集中檢疫所檢疫，2月22日接受檢疫期滿前採檢，結果為陰性，檢疫期滿後，由仲介安排至其他住所自主健康管理，2月26日搭乘專車至醫院自費採檢，因核酸檢測未確定，27日先行收治住院隔離，同日及3月2日進行核酸檢驗，於今日確診。
dice_coefficient 0.6990291262135923
4 個案檢疫期滿後，由仲介安排至其他住所自主健康管理，2月26日搭乘專車至醫院自費採檢，因核酸檢測未確定，27日先行

## 5. Overlap coefficient

In [24]:
## Overlap 

def Overlap(doc1, doc2):
    doc1 = set(doc1)
    doc2 = set(doc2)
    temp=0
    for i in doc1:
        if i in doc2:
            temp=temp+1
    overlap_coefficient=float(temp/(min(len(doc2),len(doc1))))#交集
    return overlap_coefficient
doc1_index = 0
for ws in doc_ws[0]:
    overlap_=[]
    doc2_index= 0
    for ws_x in doc_ws[1]:
        

        overlap_.append(Overlap(ws, ws_x)) #dice
        doc2_index+=1
    
    print(doc1_index,text[0][doc1_index])
    print(overlap_.index(max(overlap_)),text[1][overlap_.index(max(overlap_))])
    print("overlap_coefficient",max(overlap_)) 
    doc1_index+=1
# df = pd.DataFrame([doc1_index,
# text[0][doc1_index],
# overlap_.index(max(overlap_)),
# text[1][overlap_.index(max(overlap_))]
# ,max(overlap_)]
# , columns=["document1_index",
#  "document1",
#  "document2_index",
#  "document2",
#  "overlap_coefficient"])

0 （台灣英文新聞／醫藥組　綜合報導）中央流行疫情指揮中心今(4)日公布國內新增2例武漢肺炎（COVID-19）境外移入確定病例(案960、961)，分別自奈及利亞及菲律賓入境。
0 〔記者林惠琴／台北報導〕中央流行疫情指揮中心今日公布，武漢肺炎（新型冠狀病毒病，COVID-19）新增2例境外移入，分別自奈及利亞及菲律賓入境。
overlap_coefficient 0.7142857142857143
1 指揮中心表示，案960為奈及利亞籍50多歲男性，長期居住台灣，並持有我國居留證，今(2021)年1月8日返回奈及利亞奔喪，在當地曾於1月18日出現輕微咳嗽，經自行服藥後症狀緩解。
1 指揮中心發言人莊人祥表示，新增的案960為奈及利亞籍50多歲男性，長期居住台灣，並持有我國居留證，今年1月8日返回奈及利亞奔喪，在當地曾於1月18日出現輕微咳嗽，經自行服藥後症狀緩解。
overlap_coefficient 0.9047619047619048
2 個案2月28日返台，持有搭機前3日內檢驗陰性報告，入境後至防疫旅館檢疫，3月2日因全身倦怠及有慢性病之就醫需求，由衛生單位安排就醫採檢，於今日確診。個案就醫時接觸之相關人員皆有適當防護，故無匡列接觸者。
2 該名個案2月28日返台，持有搭機前3日內檢驗陰性報告，入境後至防疫旅館檢疫，3月2日因全身倦怠及有慢性病之就醫需求，由衛生單位安排就醫採檢，於今日確診。就醫時接觸相關人員皆有適當防護，無匡列接觸者。
overlap_coefficient 0.9803921568627451
3 案961為菲律賓籍20多歲男性移工，今年2月9日來台工作，持有搭機前3日內檢驗陰性報告，入境後至集中檢疫所檢疫，2月22日接受檢疫期滿前採檢，結果為陰性。
3 案961為菲律賓籍20多歲男性移工，今年2月9日來台工作，持有搭機前3日內檢驗陰性報告，入境後至集中檢疫所檢疫，2月22日接受檢疫期滿前採檢，結果為陰性，檢疫期滿後，由仲介安排至其他住所自主健康管理，2月26日搭乘專車至醫院自費採檢，因核酸檢測未確定，27日先行收治住院隔離，同日及3月2日進行核酸檢驗，於今日確診。
overlap_coefficient 1.0
4 個案檢疫期滿後，由仲介安排至其他住所自主健康管理，2月26日搭乘專車至醫院自費採檢，因核酸檢測未確定，27日先行收治

IndexError: list index out of range

In [25]:
df

18日  19  1月  2021  20多  22日  23  26日  27日  28日  ...  適當  醫藥組  醫院  長期  防疫  \
0     0   1   0     0    0    0   0    0    0    0  ...   0    0   0   0   0   
1     1   0   2     0    0    0   0    0    0    0  ...   0    0   0   1   0   
2     0   0   0     0    0    0   0    0    0    1  ...   1    0   0   0   1   
3     0   0   0     0    1    1   0    1    1    0  ...   0    0   1   0   0   
4     0   0   0     0    0    0   0    0    0    0  ...   1    0   0   0   0   
5     0   0   0     0    0    0   1    0    0    0  ...   0    0   0   0   0   
6     0   1   0     0    0    0   0    0    0    0  ...   0    1   0   0   0   
7     1   0   2     1    0    0   0    0    0    0  ...   0    0   0   1   0   
8     0   0   0     0    0    0   0    0    0    1  ...   1    0   0   0   1   
9     0   0   0     0    1    1   0    0    0    0  ...   0    0   0   0   0   
10    0   0   0     0    0    0   0    1    1    0  ...   0    0   1   0   0   
11    0   0   0     0    0    0   0    0    0    0  ...   1    0   0   0   0   
12    0   0   0     0    0    0   1    0    0    0  ...   0    0   0   0   0   

    防護  陰性  隔離  集中  需求  
0    0   0   0   0   0  
1    0   0   0   0   0  
2    1   1   0   0   1  
3    0   2   1   1   0  
4    1   0   1   0   0  
5    0   0   2   0   0  
6    0   0   0   0   0  
7    0   0   0   0   0  
8    1   1   0   0   1  
9    0   2   0   1   0  
10   0   0   1   0   0  
11   1   0   1   0   0  
12   0   0   2   0   0  

[13 rows x 144 columns]

## 6. cosine similarity

In [12]:
## use space to tokenize
doc_ws_space = []
for doc in doc_ws:
    ws_space = []
    for word in doc:
        ws_space.append('  '.join(word))
    doc_ws_space.append(ws_space)

In [13]:
# Scikit Learn
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# tranditional chinese stopword 
stpwrdpath ="stopword.txt"
with open(stpwrdpath, 'rb') as fp:
    stopword = fp.read().decode('utf-8')  
stpwrdlst = stopword.splitlines()
count_vectorizer=CountVectorizer(stop_words=stpwrdlst) #建立詞袋資料結構
# Create the Document Term Matrix
sparse_matrix = count_vectorizer.fit_transform(doc_ws_space[1]+doc_ws_space[0])
# OPTIONAL: Convert Sparse Matrix to Pandas Dataframe if you want to see the word frequencies.
doc_term_matrix = sparse_matrix.todense()
df = pd.DataFrame(doc_term_matrix, 
                  columns=count_vectorizer.get_feature_names(), )


In [14]:
# Compute Cosine Similarity
from sklearn.metrics.pairwise import cosine_similarity
cosine_matrix = cosine_similarity(df, df)
#> [[ 1.          0.48927489  0.37139068]
#>  [ 0.48927489  1.          0.38829014]
#>  [ 0.37139068  0.38829014  1.        ]]



In [17]:
# find the most similar document
sim= []
for index in range(len(doc_ws[0])):
    i = np.where(cosine_matrix[index][7:] ==max(cosine_matrix[index][7:]))
    print(i)
    print(text[0][index])
    print(text[1][int(i[0])])
    print(max(cosine_matrix[index][7:]))

(array([5], dtype=int64),)
（台灣英文新聞／醫藥組　綜合報導）中央流行疫情指揮中心今(4)日公布國內新增2例武漢肺炎（COVID-19）境外移入確定病例(案960、961)，分別自奈及利亞及菲律賓入境。
指揮中心統計，截至目前國內累計960例武漢肺炎，分別為844例境外移入，77例本土病例，36例敦睦艦隊、2例航空器感染及1例不明；另1例（案530）移除為空號。確診個案中9人死亡、928人解除隔離、23人住院隔離中。
0.13900960937138318
(array([0], dtype=int64),)
指揮中心表示，案960為奈及利亞籍50多歲男性，長期居住台灣，並持有我國居留證，今(2021)年1月8日返回奈及利亞奔喪，在當地曾於1月18日出現輕微咳嗽，經自行服藥後症狀緩解。
〔記者林惠琴／台北報導〕中央流行疫情指揮中心今日公布，武漢肺炎（新型冠狀病毒病，COVID-19）新增2例境外移入，分別自奈及利亞及菲律賓入境。
0.9240616554505463
(array([1], dtype=int64),)
個案2月28日返台，持有搭機前3日內檢驗陰性報告，入境後至防疫旅館檢疫，3月2日因全身倦怠及有慢性病之就醫需求，由衛生單位安排就醫採檢，於今日確診。個案就醫時接觸之相關人員皆有適當防護，故無匡列接觸者。
指揮中心發言人莊人祥表示，新增的案960為奈及利亞籍50多歲男性，長期居住台灣，並持有我國居留證，今年1月8日返回奈及利亞奔喪，在當地曾於1月18日出現輕微咳嗽，經自行服藥後症狀緩解。
0.9893262509092327
(array([2], dtype=int64),)
案961為菲律賓籍20多歲男性移工，今年2月9日來台工作，持有搭機前3日內檢驗陰性報告，入境後至集中檢疫所檢疫，2月22日接受檢疫期滿前採檢，結果為陰性。
該名個案2月28日返台，持有搭機前3日內檢驗陰性報告，入境後至防疫旅館檢疫，3月2日因全身倦怠及有慢性病之就醫需求，由衛生單位安排就醫採檢，於今日確診。就醫時接觸相關人員皆有適當防護，無匡列接觸者。
0.7777811026587883
(array([4], dtype=int64),)
個案檢疫期滿後，由仲介安排至其他住所自主健康管理，2月26日搭乘專車至醫院自費採檢，因核酸檢測未確定，27日先